# Generated by Django 2.1.7 on 2019-03-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytm_history',
            name='MERC_UNQ_REF',
            field=models.CharField(default='not_set', max_length=30, verbose_name='MERC_UNQ_REF'),
        ),
    ]
