# Generated by Django 2.1.7 on 2019-03-29 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0002_paytm_history_merc_unq_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paytm_history',
            name='user',
        ),
    ]
