# Generated by Django 2.1.7 on 2019-03-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0005_paytm_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytm_history',
            name='MERC_UNQ_REF',
            field=models.IntegerField(verbose_name='USER ID'),
        ),
    ]
